apiVersion: v1
kind: ServiceAccount
metadata:
  name: asyncvtp-uploads
  {{- with .Values.objectStorage.serviceAccount.roleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ . | quote }}
  {{- end }}
  labels:
    {{- include "asyncvtp.labels" . | nindent 4 }}
